### PR TITLE
IDA 7 fix for endianness in ida_utilities

### PR DESCRIPTION
**Pull request by stek29**

### CODE REVIEW

**Comment by bazad** [comment]
@stek29 Thanks for the IDA7 fix! I'm actually going to be pushing a major update soon (including automatic class generation!), so it might be awhile before I merge this in.

**Comment by stek29** [comment]
Np, just wanted to share what I found :)

**Comment by stek29** [comment]
Looking forward for updates :D

**Comment by bazad** [comment]
Thanks again for your contribution! I merged it locally, but GitHub doesn't recognize the merge since I rebased your commit onto my recent updates. Next time I guess I'll just ask you to do the rebase.

**Pull request closed without merging**
