### PR TITLE
IDA 7 fixes

### PR DESCRIPTION
**Pull request by stek29**

### CODE REVIEW

**Comment by bazad** [comment]
Thanks for the new fixes! Do you know if these changes are compatible with IDA 6.95?

**Comment by stek29** [comment]
@bazad No, sadly. And I can't really test it.
However they should work, but I'm not sure about idc.OpStroffEx and idaapi.is_ident_char ones.

**Comment by bazad** [comment]
@stek29 I've tested the pull request and have a small change to reintroduce support for 6.95. I'd appreciate if you could test it again on IDA7 before I merge. Could you grant me push access to the ida7 branch and check if everything still works?

**Comment by stek29** [comment]
@bazad how would I? "Allow edits from maintainers" is checked.

**Comment by bazad** [comment]
@stek29 Ah, sorry, I should have tried first. I've added the 6.95 fixes, let me know if it looks good.

**Comment by stek29** [comment]
lgtm, would test in a couple of hours

**Comment by stek29** [comment]
Sorry, forgot to respond -- it worked fine for me

**Pull request merged**
